# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dc98de3416ec156c2cbc7be47f164419df2138b47e8f42d35a3dc8bac4e12edc851d20ce0f855d33ec1c6e638e48fd205f150dd4a401161198308f921e53b5e

test:
  secret_key_base: d1d0c87a2f7eae171ec18a28a6f4abfa1d51db30573dfcb6a82b0d154c1cdcd60fa2a700c09ed640ce63da38e2f1bbeaf5953cb0541cc76575aff09f29e61834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

